### ISSUE TITLE
add &secret= feeder lock method

### ISSUE THREAD

**Issue by JWo1F** [grandrew/plotti.co#7]
Hi! Thank you for this service. I think, will be good create initializing URL. For example, `plotti/init/publicCode?secret=secretCode&size=20` where `publicCode` is code for view graph, `secretCode` is code for update graph and `size` is width.
Then we can update plot at this address: `plotti/update/secretCode?d=...` and see: `plotti/publicCode`

BTW, why do you use `d=1,1,1`, not `red=1.0&blue=2.0&...`?

**Comment by grandrew** [comment]
Thank you for your suggestion! 
I think that it may be easier to implement a secret in an ordinary update path as additional query paramener: `http://plotti.co/sdfasdfaasfd?d=1,2,3&secret=123` so that it will lock to secret instead of IP

as for the request notation - it is done to simplify it both ways: the string is processed as a single argument on the server and at the client code, also it enables doing very elegant things with unix shell, like one mentioned here http://stackoverflow.com/questions/4134314/live-plot-from-stdin/36039289#36039289

**Comment by JWo1F** [comment]
@grandrew yeap, it will be cool.

And, I think, we need to add a "legend" argument. What do you think?

**Comment by grandrew** [comment]
@JWo1F legend is a static information, you can just add any style "legends" using color coding doc at http://plotti.co/#choosing-color and some trivial CSS wrap-up, or even in your WYSIWYG editor, but having nice examples in the docs would be great. Adding it to my to-do
